name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          npmAlwaysAuth: true
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          echo 'registry: https://registry.npmjs.org/' >> .yarnrc
          yarn workspaces foreach -v --no-private npm publish --access public 