name: "publish npm"

on: 
  push:
    branches:
      - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: yarn install
              run: yarn install
            - name: publish
              run: |
                yarn config set -H 'npmAuthToken' "${{secrets.NPM_TOKEN}}"
                yarn workspaces foreach -v --no-private npm publish --access public --tolerate-republish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}