name: "publish"

on: 
  push:
    branches:
      - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: yarn install
              run: yarn install
            - name: publish
              run: |
                cd $path
                yarn install
                echo "@npjosem:registry=https://npm.pkg.github.com/"> ./.npmrc
                echo "//npm.pkg.github.com/:_authToken=${{ steps.generate-token.outputs.token }}" >> ./.npmrc
                cat ./.npmrc
                yarn workspaces foreach -v npm publish --access private --tolerate-republish