name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Deleted .npmrc
        run: rm -rf ~/.npmrc

      - name: Configure npm authentication
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > ~/.npmrc
    
      - name: Verify npm authentication
        run: cat ~/.npmrc

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          npmAlwaysAuth: true
        run:
          yarn workspaces foreach -R -v --no-private npm publish --access public 