name: Publish to Github Packages
 
on:
  push:
    branches:
      - main
 
jobs:
  publish:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
 
      - name: Set up Yarn 4
        run: |
          yarn set version berry
 
      - name: Autenticarse con el registro de Github Packages
        run: |
          cd allure/
          echo 'npmRegistries:' >> ./.yarnrc.yml
          echo ' "https://npm.pkg.github.com":' >> ./.yarnrc.yml
          echo '    npmAuthToken: "${{ secrets.AUTH_GITHUB_TOKEN }}"' >> ./.yarnrc.yml
          echo 'npmScopes:' >> ./.yarnrc.yml
          echo '  npjosem:' >> ./.yarnrc.yml
          echo '    npmRegistryServer: "https://npm.pkg.github.com"' >> ./.yarnrc.yml
          cat ./.yarnrc.yml
         
      - name: Ejecutar yarn install
        run: yarn install
 
      - name: Publish to NPM
        run: |
          yarn workspaces foreach --all -v npm publish --access restricted --tolerate-republish -tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}